"""
tests/regression/test_grammar_integrity.py

Regression tests that directly guard against the __ANON_* grammar corruption
bug introduced in commit e8956c9 (Aug 3 2026).

These tests MUST be run before any synthetic data generation to ensure
grammar.py is a valid, clean conversion of grammar.lark.
"""
import re
from pathlib import Path

import pytest

PROJECT_ROOT      = Path(__file__).resolve().parents[2]
GRAMMAR_PY_PATH   = PROJECT_ROOT / "src" / "data" / "grammar.py"
GRAMMAR_LARK_PATH = PROJECT_ROOT / "src" / "data" / "grammar.lark"
# ---------------------------------------------------------------------------
# 1. File existence / configuration
# ---------------------------------------------------------------------------

def test_grammar_py_exists():
    """grammar.py must exist (generated by generate_base_grammar.py)."""
    assert GRAMMAR_PY_PATH.exists(), (
        f"{GRAMMAR_PY_PATH} not found. "
        "Run: uv run scripts/generate_base_grammar.py"
    )



# ---------------------------------------------------------------------------
# 2. The __ANON_* corruption guard — THE core regression test
# ---------------------------------------------------------------------------

def test_no_anon_tokens_in_grammar_py():
    """
    No __ANON_* placeholder should appear anywhere in grammar.py.
    If generate_base_grammar.py is working correctly, all anonymous
    terminals are resolved to their literal LaTeX values (e.g. '^{', '}').
    """
    content = GRAMMAR_PY_PATH.read_text(encoding="utf-8")
    anon_matches = re.findall(r"(?<!__REGEX_)__ANON_\d+", content)
    assert not anon_matches, (
        f"grammar.py contains unresolved __ANON_* tokens: {set(anon_matches)}. "
        "Re-run scripts/generate_base_grammar.py to regenerate."
    )


def test_grammar_py_is_not_pcfg_output():
    """
    grammar.py must NOT contain scraped frequency data.
    The header comment confirms whether pCFG_generator.py was mistakenly
    used to overwrite grammar.py (as happened in commit e8956c9).
    """
    first_lines = GRAMMAR_PY_PATH.read_text(encoding="utf-8")[:300]
    assert "rule_frequencies" not in first_lines, (
        "grammar.py header references 'rule_frequencies.json' — this file "
        "was generated by pCFG_generator.py (which uses scraped data) instead "
        "of generate_base_grammar.py. Re-run: uv run scripts/generate_base_grammar.py"
    )


# ---------------------------------------------------------------------------
# 3. Structural integrity checks
# ---------------------------------------------------------------------------

def test_grammar_py_imports_cleanly():
    """grammar.py must be importable and expose rules, non_terminals, terminals."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("grammar_under_test", GRAMMAR_PY_PATH)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    assert hasattr(mod, "rules"), "grammar.py missing 'rules' dict"
    assert hasattr(mod, "non_terminals"), "grammar.py missing 'non_terminals' set"
    assert hasattr(mod, "terminals"), "grammar.py missing 'terminals' set"
    assert isinstance(mod.rules, dict), "'rules' must be a dict"
    assert isinstance(mod.non_terminals, set), "'non_terminals' must be a set"
    assert len(mod.rules) > 0, "'rules' dict is empty"
    assert len(mod.non_terminals) > 0, "'non_terminals' set is empty"


def test_all_rule_rhs_are_resolvable():
    """
    Every symbol in every rule production must be either:
      - a key in non_terminals  (it will be expanded recursively), OR
      - a plain string literal  (returned as-is by the generator).
    No symbol should look like '__ANON_*' or '<TERMINAL_NAME>'.
    """
    import importlib.util
    spec = importlib.util.spec_from_file_location("grammar_under_test", GRAMMAR_PY_PATH)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    anon_pattern    = re.compile(r"^__ANON_\d+$")
    bracket_pattern = re.compile(r"^<[A-Z_]+>$")

    violations = []
    for lhs, (productions, _) in mod.rules.items():
        for rhs in productions:
            for sym in rhs:
                if anon_pattern.match(sym) or bracket_pattern.match(sym):
                    violations.append(f"  rule '{lhs}' contains unresolved symbol: {sym!r}")

    assert not violations, (
        "Unresolved symbols found in grammar.py rules:\n" + "\n".join(violations)
    )


def test_grammar_py_has_required_non_terminals():
    """Key structural non-terminals must be present."""
    import importlib.util
    spec = importlib.util.spec_from_file_location("grammar_under_test", GRAMMAR_PY_PATH)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    required = {"START", "EXPR", "TERM", "FACTOR", "ATOM", "RELATION", "FRAC", "SCRIPTED"}
    missing  = required - mod.non_terminals
    assert not missing, f"grammar.py is missing required non-terminals: {missing}"


def test_uniform_probabilities():
    """
    In the base grammar, all productions for a given rule should have
    equal probability (uniform distribution — 1/n for n alternatives).
    """
    import importlib.util
    spec = importlib.util.spec_from_file_location("grammar_under_test", GRAMMAR_PY_PATH)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    for lhs, (productions, probs) in mod.rules.items():
        n = len(productions)
        expected = 1.0 / n
        for p in probs:
            assert abs(p - expected) < 1e-9, (
                f"Rule '{lhs}' has non-uniform probabilities: {probs}. "
                "Base grammar must use uniform distribution."
            )
